server:
  port: 8001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/public?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul'
    username: root
    password: 1234

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization : true
    hibernate:
      ddl-auto: update        # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true      # 쿼리 로그 포맷 (정렬)
        show_sql: true        # 쿼리 로그 출력

  # redis
  redis:
    host: localhost
    port: 6379

  session:
    store-type: redis

logging:
  level:
    root: info


# swagger
springdoc:
  packages-to-scan: com.yblog
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: swagger.html            # Swagger UI 경로 => localhost:8000/demo-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true


#spring:
#  # H2 Database 설정
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: 'jdbc:h2:mem:test'   # H2 DB 연결 주소 (In-Memory Mode)
#    #url: 'jdbc:h2:~/test'    # H2 DB 연결 주소 (Embedded Mode)
#    username: admin        # H2 DB 접속 ID (사용자 지정)
#    password: admin        # H2 DB 접속 PW (사용자 지정)

# H2 Console 설정
#h2:
#  console: # H2 DB를 웹에서 관리할 수 있는 기능
#    enabled: true           # H2 Console 사용 여부
#    path: /h2-console       # H2 Console 접속 주소